name: Test & Commit

on:
  push:
    branches:
      - actions-test

jobs:
  test_commit:
    runs-on: macos-latest

    env:
      DIFF_BOOLEAN: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    # - name: Install Gems
    #   run: |
    #       bundle install
    #
    # - name: Run Tests
    #   run: |
    #     rubocop
    #     rspec

    - name: Test Variable Reset
      run: echo "DIFF_BOOLEAN=true" >> $GITHUB_ENV

    - name: Echo Variable Value
      run: echo $DIFF_BOOLEAN

    # - name: Test File Creation
    #   run: touch test.txt
    #
    # - name: Check For Changes
    #   run: |
    #     if git diff --exit-code; then
    #       echo "{DIFF_BOOLEAN}={true}" >> $GITHUB_ENV
    #     fi

    # - name: Commit If Changes
    #   if: env.DIFF_BOOLEAN == 'true'
    #   run: |
    #     git config user.name "GitHub Action"
    #     git config user.email "github-actions@github.com"
    #     git add .
    #     git commit -m "Automated commit. Reflects $(git rev-parse --abbrev-ref ${{ github.ref }}) branch commit $(git rev-parse --short ${{ github.sha }})."
