name: Test & Commit

on:
  push:
    branches:
      - actions-test

jobs:
  test_commit:
    runs-on: macos-latest

    env:
      DIFF_BOOLEAN: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    # - name: Install Gems
    #   run: |
    #       bundle install
    #
    # - name: Run Tests
    #   run: |
    #     rubocop
    #     rspec

    - name: Check For Changes
      run: |
        if git diff --exit-code; then
          echo "::set-env name=DIFF_BOOLEAN::true"
        fi

    - name: Commit If Changes
      if: {{ env.DIFF_BOOLEAN }}
      run: echo "Commit required."
        # git config user.name "GitHub Action"
        # git config user.email "github-actions@github.com"
