name: RSpec Test, Commit & Push

on: [push]

jobs:
  RSpec_Tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - run: bundle install

    - name: commit
    - run: |
      git config user.name github-actions
      git config user.email github-actions@github.com
      git add .
      git commit -m "GitHub Action commit."
      git push
