name: RSpec

on: [push]

jobs:
  RSpec_Tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - run: bundle install
    - run: bundle exec rspec

    - name: commit
    - run: |
      git commit -am "Automated workflow commit."
      git push
