name: RSpec

on: [push]

jobs:
  RSpec_Tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - run: bundle install
    - run: rspec
