name: SimpleCov_Shield_Badge

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GITHUB_USER: "JoshSinyor"
      GITHUB_MAIL: ${{ secrets.MAIL }}
      GITHUB_ORG: "JoshSinyor"
      GITHUB_REPO: "bank_tech_test"
      GITHUB_ACCESS_TOKEN: ${{ secrets.TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0

    - name: Run bundle install
      run: bundle install

    - run: bundle exec rspec
